version: 2.1
jobs:
  build-playwright-job:
    docker:
      - image: cimg/node:16.14
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: node-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Install Playwright
          command: npx playwright install
      - run:
          name: Run Playwright Tests
          command: npm Tests
          
workflows:
  build-playwright:
    jobs:
      - build-playwright-job:
          filters:
            branches:
              only: master