version: 2.1
jobs:
  build-and-push-image-job:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -f _deploy/docker/dockerfile -t $IMAGE_NAME:playwright-$CIRCLE_SHA1 .
      - run:
          name: Push Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:playwright-$CIRCLE_SHA1
          
workflows:
  build-playwright:
    jobs:
      - build-and-push-image-job:
          filters:
            branches:
              only: master
